name: CI-names-sorter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x  # Replace with your desired .NET Core version

    - name: Restore dependencies
      run: dotnet restore NameSorterApp/NameSorterApp/name-sorter.csproj

    - name: Build
      run: dotnet build NameSorterApp/NameSorterApp/name-sorter.csproj --configuration Release

    - name: Test
      run: dotnet test NameSorterApp/name-sorter.Test/name-sorter.Tests.csproj --configuration Release --no-build
